Occasions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_view
from rest_framework_simplejwt import views as jwt_views

from delivery.views import SuperAdminListDelivery
from outlets.stock_views.views import SuperAdminListStock
from rest_framework import serializers, viewsets, routers


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()

# router.register('v1/banner', BannerImageViewSet)


urlpatterns = [
    path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.stocks_api.urls', namespace='stocks_api')),
    path('api/', include('api.outlets_api.urls', namespace='outlets_api')),
    path('api/', include('api.category_api.urls', namespace='category_api')),
    path('api/', include('api.outletcart_api.urls', namespace='outlet_cart')),
    path('api/', include('api.delivery_api.urls', namespace='delivery_api')),
    path('api/', include('api.country_api.urls', namespace='country_api')),
    path('admin/', admin.site.urls),
    path('outlets/', include('outlets.urls', namespace="outlets")),
    path('category/', include('outlets.category_views.urls', namespace="category")),
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('stocks/', SuperAdminListStock.as_view(), name='admin_stock'),
    path('delivery/', SuperAdminListDelivery.as_view(), name="admin_delivery"),
    path('api/v1/users/', include('social_app.urls', namespace="users_api")),
    # path('api/auth/', include('rest_framework.urls')),
    # path('rest-auth/', include('rest_auth.urls')),
    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
    # path('rest-auth/facebook/', FacebookLogin.as_view(), name='fb_login'),
    # path('oauth2/', include('oauth2_provider.urls', namespace='oauth2')),
    path('activity/', include(('actstream.urls', 'actstream'), namespace="activity")),
    path('api/v1/login/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/login/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
] +\
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

outlets/category_views/urls.py
from django.urls import path

from outlets.category_views.views import AddCategory, ListCategory, ListSubCategory, EditCategory, DeleteCategory

app_name = 'category'

urlpatterns = [
    path('create/', AddCategory.as_view(), name='create'),
    path('', ListCategory.as_view(), name='list_category'),
    path('<int:pk>/sub-category/', ListSubCategory.as_view(), name='sub-category'),
    path('<int:pk>/edit', EditCategory.as_view(), name='edit'),
    path('<int:pk>/delete', DeleteCategory.as_view(), name='delete')

]

outlets/invoice_views/urls.py
from django.urls import path

from outlets.invoice_views.views import DetailInvoice, PDFDetailInvoiceView

urlpatterns = [
    path('<int:pk>/', DetailInvoice.as_view(), name='detail'),
    path('<int:pk>/pdf/', view=PDFDetailInvoiceView.as_view(), name="pdf"),

]

outlets/stock_views/urls.py
from django.urls import path

from outlets.stock_views.views import ListStock, DetailStock, AddStock, AddItem, EditStock, DeleteStock, search_items

app_name = 'stocks'

urlpatterns = [
    path('', ListStock.as_view(), name="list"),
    path('list/', ListStock.as_view(), name="list"),
    path('create/', AddStock.as_view(), name="create"),
    path('add-item/', AddItem.as_view(), name="add_item"),
    path('<int:pk>/', DetailStock.as_view(), name="detail"),
    path('<int:pk>/update/', EditStock.as_view(), name="update"),
    path('<int:pk>/delete/', DeleteStock.as_view(), name="delete"),
    path('search_item/', search_items, name="search_item"),

]

outlets/urls.py
from django.urls import path, include

app_name = 'outlets'

urlpatterns = [
    path('', include(('outlets.outlets_views.urls', 'outlets'), namespace="outlet")),
    path('<int:outlet_id>/stocks/', include(('outlets.stock_views.urls', 'outlets'), namespace="stocks")),
    path('<int:outlet_id>/delivery/', include(('delivery.deliverypolicy_views.urls', 'delivery'), namespace="delivery")),
    path('<int:outlet_id>/orders/', include(('delivery.order_views.urls', 'delivery'), namespace="orders")),
    path('admins/', include(('social_app.urls', 'social_app'), namespace="social_app")),

]

outlets/category_views/views.py
from django.contrib import messages
from django.urls import reverse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from outlets.category_models import Category
from outlets.forms import CategoryForm


class ListCategory(ListView):
    model = Category
    template_name = "outlets/category/list_category.html"
    context_object_name = "category_status"

    def get_queryset(self):
        queryset = {'active': Category.objects.get_categories(),
                   'inactive': Category.objects.filter(level=0, disabled=True)
                    }
        return queryset


class ListSubCategory(ListView):
    queryset = Category.objects.get_sub_categories()
    template_name = "outlets/category/list_sub_category.html"

    def get_queryset(self):
        category_id = self.kwargs['pk']
        return Category.objects.filter(parent_id=category_id)


class AddCategory(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = "outlets/category/add_category.html"

    def get_success_url(self):
        return reverse('category:list_category')


class EditCategory(UpdateView):
    model = Category
    form_class = CategoryForm
    queryset = Category.objects.all()
    template_name = "outlets/category/add_category.html"

    def get_queryset(self):
        category_id = self.kwargs['pk']
        return Category.objects.filter(id=category_id)

    def get_success_url(self):
        return reverse('category:list_category')


class DeleteCategory(DeleteView):
    model = Category
    queryset = Category.objects.all()

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, ** kwargs)

    def get_success_url(self):
        messages.success(self.request, "{name} {message}".format(name=self.object.category_name,
                                                                 message="had been deleted."))
        return reverse('category:list_category')

outlets/invoice_views/views.py
from django.conf import settings
from django.http import Http404
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from easy_pdf.views import PDFTemplateView

from libs.mixins import OutletPermissionCheckMixin, OutletKwargForFormMixin, OutletContextForTemplatesMixin
from outlets.models import OutletInvoice


class DetailInvoice(OutletPermissionCheckMixin, OutletKwargForFormMixin, OutletContextForTemplatesMixin, DetailView):
    model = OutletInvoice
    queryset = OutletInvoice.objects.all()
    template_name = 'outlets/invoice/invoice_detail.html'

    def get_queryset(self):
        return super(DetailInvoice, self).get_queryset().filter(associated_outlet=self.outlet)

    def get_context_data(self, **kwargs):
        context = super(DetailInvoice, self).get_context_data(**kwargs)
        return context


class PDFDetailInvoiceView(OutletPermissionCheckMixin, PDFTemplateView):
    model = OutletInvoice
    template_name = 'outlets/invoice/invoice_pdf.html'

    pk_url_kwarg = 'pk'
    base_url = 'file://' + settings.STATIC_ROOT

    def get_download_filename(self):
        return "Invoice #" + self.object.invoice_number + ".pdf"

    def get_object(self, **kwargs):
        try:
            self.object = OutletInvoice.objects.get(pk=kwargs.get(self.pk_url_kwarg))
            return self.object
        except OutletInvoice.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': OutletInvoice._meta.verbose_name})

    def get_context_data(self, **kwargs):
        self.get_object(**kwargs)
        context = super(PDFDetailInvoiceView, self).get_context_data(pagesize='A4',
                                                                title='Invoice #{}'.format(
                                                                    self.object.invoice_number),
                                                                **kwargs)
        context['object'] = self.object
        return context



#for user front end
class PDFInvoiceUserEndView(PDFTemplateView):
    model = OutletInvoice
    template_name = 'outlets/invoice/invoice_pdf.html'

    pk_url_kwarg = 'pk'
    base_url = 'file://' + settings.STATIC_ROOT

    def get_download_filename(self):
        return "Invoice #" + self.object.invoice_number + ".pdf"

    def get_object(self, **kwargs):
        try:
            self.object = OutletInvoice.objects.get(pk=kwargs.get(self.pk_url_kwarg))
            return self.object
        except OutletInvoice.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': OutletInvoice._meta.verbose_name})

    def get_context_data(self, **kwargs):
        self.get_object(**kwargs)
        context = super(PDFDetailInvoiceView, self).get_context_data(pagesize='A4',
                                                                     title='Invoice #{}'.format(
                                                                         self.object.invoice_number),
                                                                     **kwargs)
        context['object'] = self.object
        return context

outlets/outlets_views/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from libs.mixins import IsSuperAdminUserMixin
from outlets.forms import OutletsAdminForm
from outlets.outlet_models import Outlet
from outlets.outlets_views.filter import OutletFilter


class OutletCreate(CreateView):
    template_name = 'outlets/outlet/create_outlet.html'
    form_class = OutletsAdminForm
    queryset = Outlet.objects.all()

    def get_success_url(self):
        return reverse('outlets:outlet:list')


class OutletList(IsSuperAdminUserMixin, ListView):
    template_name = "outlets/outlet/list_outlets.html"
    queryset = Outlet.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = OutletFilter(self.request.GET, queryset=self.get_queryset())
        return context


class OutletDetail(DetailView):
    # model = Outlet
    # queryset = Outlet.objects.all()
    template_name = 'outlets/outlet/detail_outlet.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Outlet, id=id_)

    def get_context_data(self, **kwargs):
        context = super(OutletDetail, self).get_context_data(**kwargs)
        context["outlet_id"] = self.kwargs.get("id")
        return context


class OutletUpdate(IsSuperAdminUserMixin, UpdateView):
    template_name = 'outlets/outlet/create_outlet.html'
    form_class = OutletsAdminForm
    queryset = Outlet.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Outlet, id=id_)

    # def form_valid(self, form):
    #     print(form.cleaned_data)
    #     return super().form_valid(form)

    def get_success_url(self):
        return reverse('outlets:outlet:list')


class OutletDelete(IsSuperAdminUserMixin, DeleteView):
    model = Outlet
    queryset = Outlet.objects.all()

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, "{message}".format(
            message="The outlet has been deleted"
        ))
        return reverse('outlets:outlet:list')

outlets/stock_views/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from libs.mixins import OutletContextForTemplatesMixin, OutletKwargForFormMixin, OutletPermissionCheckMixin, \
    IsSuperAdminUserMixin
from outlets.forms import OutletStockAdminForm, OutletItemAdminForm
from outlets.outlet_models import Outlet

from outlets.stock_models import OutletStock, OutletItem, BaseItem


class ListStock(OutletPermissionCheckMixin, OutletContextForTemplatesMixin, ListView):
    model = OutletStock
    queryset = OutletStock.objects.all()
    paginate_by = 12
    template_name = "outlets/stock/list_stocks.html"

    def get_queryset(self):
        qs = super(ListStock, self).get_queryset().filter(outlet=self.outlet)
        # self.filter = StocksFilter(self.request.GET, queryset=qs)
        return qs

    def get_context_data(self, **kwargs):
        context = super(ListStock, self).get_context_data(**kwargs)
        # context['type2'] = self.outlet.get_category_templates(1)
        # context['type3'] = self.outlet.get_category_templates(2)
        # context['filter'] = self.filter
        return context


class DetailStock(OutletPermissionCheckMixin, OutletContextForTemplatesMixin, DetailView):
    model = OutletStock
    queryset = OutletStock.objects.all()
    template_name = 'outlets/stock/detail_stock.html'

    def get_queryset(self):
        qs = super(DetailStock, self).get_queryset().filter(outlet=self.outlet)
        return qs


class AddStock(OutletPermissionCheckMixin, OutletContextForTemplatesMixin, OutletKwargForFormMixin,
               CreateView):
    model = OutletStock
    form_class = OutletStockAdminForm
    template_name = 'outlets/stock/add_stock.html'

    def get_success_url(self):
        return reverse('outlets:stocks:detail', kwargs={'outlet_id': self.outlet.id, 'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(AddStock, self).get_context_data(**kwargs)
        context['item_form'] = OutletItemAdminForm(outlet=self.outlet)
        context['operation'] = 'add'

        return context


class AddItem(OutletPermissionCheckMixin, OutletContextForTemplatesMixin, OutletKwargForFormMixin,
              CreateView):
    model = OutletItem
    form_class = OutletItemAdminForm
    template_name = 'outlets/stock/add_item.html'

    def form_valid(self, form):
        self.object = form.save()
        return JsonResponse(dict(value=self.object.id, label=str(self.object)))

    def form_invalid(self, form):
        messages.error(self.request,
                       "{}".format(form.errors))
        return redirect(reverse('outlets:stocks:add', kwargs=dict(outlet_id=self.outlet.id)))


class EditStock(OutletPermissionCheckMixin, OutletKwargForFormMixin, OutletContextForTemplatesMixin,
                UpdateView):
    model = OutletStock
    queryset = OutletStock.objects.all()
    form_class = OutletStockAdminForm
    template_name = 'outlets/stock/add_stock.html'

    def get_queryset(self):
        return super(EditStock, self).get_queryset().filter(outlet=self.outlet)

    def get_success_url(self):
        return reverse('outlets:stocks:detail', kwargs={'outlet_id': self.outlet.id, 'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(EditStock, self).get_context_data(**kwargs)
        context['operation'] = 'Edit'
        return context


class DeleteStock(OutletPermissionCheckMixin, OutletContextForTemplatesMixin, IsSuperAdminUserMixin, DeleteView):
    model = OutletStock
    queryset = OutletStock.objects.all()

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request,
                         "{message} S.K.U - {sku}, {name}".format(
                             message="The stock has been deleted",
                             sku=self.object.sku,
                             name=self.object
                         ))
        return reverse('outlets:stocks:list', kwargs={'outlet_id': self.outlet.id})


class SuperAdminListStock(IsSuperAdminUserMixin, ListView):
    model = OutletStock
    queryset = OutletStock.objects.all()
    template_name = "outlets/stock/admin_stock_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SuperAdminListStock, self).get_context_data()
        return context


def search_items(request, outlet_id):
    query = request.GET.get('query').strip()
    q = BaseItem.objects.filter(display_name__icontains=query)
    q = [{'id': each.id, 'name': str(each)} for each in q]
    return JsonResponse(
        dict(
            items=q,
        )
    )

outlets/views.py
from django.shortcuts import render


# # Create your views here.
# from outlets.forms import OutletForm
#
#
# def outlet_create_view(request):
#     form = OutletForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#     context = {
#         'form': form
#     }
#     return render(request, "outlets/create_outlet.html", context)

templates/outlets/category/add_category.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <form role="form" method="POST" enctype="multipart/form-data">
        <div class="box-body">
            {% csrf_token%}
            {{ form.as_p }}
        </div>

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Submit&raquo;</button>
        </div>
    </form>
{% endblock %}

templates/outlets/category/list_category.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

    <section class="content-header">
        <h1>
            Categories
            <small>Category List</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="#">Category</a></li>
            <li class="active">List</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Category List</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Active Category Name</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% if category_status %}
                            {% for item in object_list.active %}
                                <tr>
                                    <td>
                                        <a href="{% url 'category:sub-category' pk=item.pk %}">
                                            {{ item.category_name }}
                                        </a>
                                        <a href ="{% url 'category:edit' pk=item.id %}" >
                                            <i class="fa fa-edit" style="margin-left: 50px;"></i>
                                        </a>
{#                                        <a href="{% url 'category:delete' pk=item.id %}">#}
{#                                            <i class="btn-danger fa fa-trash" style="margin-left: 50px;"></i>#}
{#                                        </a>#}
                                    </td>

                                </tr>
                            {% endfor %}
                            {% endif %}
                            </tbody>

                        </table>
                    <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>InActive Category Name</th>
                            </tr>
                            </thead>
                             <tbody>
                        {% if category_status.inactive %}
                            {% for item in object_list.inactive %}
                                <tr>
                                    <td>
                                        <a href="{% url 'category:sub-category' pk=item.pk %}">
                                            {{ item.category_name }}
                                        </a>
                                        <a href ="{% url 'category:edit' pk=item.id %}" >
                                            <i class="fa fa-edit" style="margin-left: 50px;"></i>
                                        </a>
{#                                        <a href="{% url 'category:delete' pk=item.id %}">#}
{#                                            <i class="btn-danger fa fa-trash" style="margin-left: 50px;"></i>#}
{#                                        </a>#}
                                    </td>

                                </tr>
                            {% endfor %}
                            {% endif %}
                        </tbody>

                        </table>

                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
{% endblock %}

templates/outlets/category/list_sub_category.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

    <section class="content-header">
        <h1>
            Sub-Categories
            <small>Sub-Category List</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="#">Sub-Category</a></li>
            <li class="active">List</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Sub-Category List</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Sub-Category Name</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in object_list %}
                                <tr>
                                    <td>
                                        {{ item.category_name }}
                                        <a href="{% url 'category:edit' pk=item.id %}">
                                            <i class="fa fa-edit" style="margin-left: 50px;"></i>
                                        </a>
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
{#    <div class="btn-bitbucket">#}
{#        <a href="{% url 'category:edit' pk=item.id %}">#}
{#            <button type="button">Update</button>#}
{#        </a>#}
{#    </div>#}
{% endblock %}