Occasions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_view
from rest_framework_simplejwt import views as jwt_views

from delivery.views import SuperAdminListDelivery
from outlets.stock_views.views import SuperAdminListStock
from rest_framework import serializers, viewsets, routers


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()

# router.register('v1/banner', BannerImageViewSet)


urlpatterns = [
    path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.stocks_api.urls', namespace='stocks_api')),
    path('api/', include('api.outlets_api.urls', namespace='outlets_api')),
    path('api/', include('api.category_api.urls', namespace='category_api')),
    path('api/', include('api.outletcart_api.urls', namespace='outlet_cart')),
    path('api/', include('api.delivery_api.urls', namespace='delivery_api')),
    path('api/', include('api.country_api.urls', namespace='country_api')),
    path('admin/', admin.site.urls),
    path('outlets/', include('outlets.urls', namespace="outlets")),
    path('category/', include('outlets.category_views.urls', namespace="category")),
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('stocks/', SuperAdminListStock.as_view(), name='admin_stock'),
    path('delivery/', SuperAdminListDelivery.as_view(), name="admin_delivery"),
    path('api/v1/users/', include('social_app.urls', namespace="users_api")),
    # path('api/auth/', include('rest_framework.urls')),
    # path('rest-auth/', include('rest_auth.urls')),
    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
    # path('rest-auth/facebook/', FacebookLogin.as_view(), name='fb_login'),
    # path('oauth2/', include('oauth2_provider.urls', namespace='oauth2')),
    path('activity/', include(('actstream.urls', 'actstream'), namespace="activity")),
    path('api/v1/login/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/login/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
] +\
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

outlets/urls.py
from django.urls import path, include

app_name = 'outlets'

urlpatterns = [
    path('', include(('outlets.outlets_views.urls', 'outlets'), namespace="outlet")),
    path('<int:outlet_id>/stocks/', include(('outlets.stock_views.urls', 'outlets'), namespace="stocks")),
    path('<int:outlet_id>/delivery/', include(('delivery.deliverypolicy_views.urls', 'delivery'), namespace="delivery")),
    path('<int:outlet_id>/orders/', include(('delivery.order_views.urls', 'delivery'), namespace="orders")),
    path('admins/', include(('social_app.urls', 'social_app'), namespace="social_app")),

]

delivery/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import signals
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from libs.constants import CURRENCY_CHOICES, STATUS_CHOICES
from libs.models import CustomModel, CustomManager
from libs.utils import get_random_secret_key, prevent_recursion


class TrackingDetailsManager(CustomManager):
    def get_queryset(self):
        return super(TrackingDetailsManager, self).get_queryset().exclude(canceled=True)

    def canceled(self):
        return super(TrackingDetailsManager, self).get_queryset().filter(canceled=True)


class DeliveryPolicy(CustomModel):
    outlet = models.ForeignKey("outlets.Outlet", verbose_name="Outlet", on_delete=models.CASCADE)
    radius = models.FloatField("Radius (in km)",unique=True, validators=[
        MinValueValidator(0, "distance is below zero.")
    ])
    price = models.FloatField("Delivery Price", help_text="tentative price", default=0,
                              validators=
                              [MinValueValidator(0, "below minimum price")])
    currency = models.FloatField("Currency", choices=CURRENCY_CHOICES, default=0, max_length=5)
    delivery_time = models.FloatField("Tentative Time to delivery(in hours)",
                                      help_text="it includes 'processing' + 'delivery' time.",
                                      validators=[
                                          MinValueValidator(0, "Value should be over zero."),
                                      ]
                                      )

    def __str__(self):
        return f"Delivery Policy {str(self.id)}"


class TrackingDetails(CustomModel):
    """
    Each invoice is going to have tracking detail with status as in STATUS CHOICES
    """
    tracking_number = models.CharField(_("Tracking Number"), max_length=15, unique=True, help_text=_("Must be unique"),
                                       blank=False)
    status = models.FloatField(_("status"), choices=STATUS_CHOICES, default=0, blank=False)
    _old_status = models.FloatField(_("old status"), choices=STATUS_CHOICES)
    date_modified = models.DateField(_("Altered Date"), help_text=_("when was order altered."))
    date_confirmed = models.DateTimeField(_("Date Confirmed"),
                                          null=True,
                                          help_text=_("when was order confirmed."))
    delivery_date = models.DateTimeField(_("Delivery Date"),
                                         null=True,
                                         help_text=_("when order is to be delivered."))
    order_placed = models.DateTimeField(_("Order Placed"), help_text=_("when was order placed."), default=timezone.now)
    order = models.OneToOneField('outlets.OutletInvoice', on_delete=models.DO_NOTHING)

    shipped_to = models.ForeignKey('social_app.ShippingAddress', on_delete=models.DO_NOTHING, blank=True, null=True)
    buyer = models.ForeignKey('social_app.OccasionUser', null=True, on_delete=models.DO_NOTHING)
    # shipped_to = models.TextField("User Address", null=True, blank=True)
    # buyer = models.("User", null=True, blank=True)

    canceled_date = models.DateTimeField("Canceled Date", null=True)
    canceled = models.NullBooleanField("Canceled", default=False)
    canceled_by = models.OneToOneField("social_app.OccasionUser", null=True, related_name="canceled", on_delete=models.CASCADE)
    # canceled_by = models.TextField("User", null=True, blank=True)
    cancel_reason = models.TextField("Cancel Reason", null=True, blank=False)

    @property
    def get_status(self):
        return STATUS_CHOICES[int(self.status)][1]

    def get_itemlines(self):
        # used in the templates
        itemlines = []
        for il_data in self.order.itemline_data.all():
            itemlines.append({'stocked_item': il_data.itemline.stocked_item,
                              'quantity': il_data.itemline.quantity,
                              'itemline_data': il_data
                              })
        return itemlines

    def reduce_stock(self):
        for itemline_invoice in self.order.itemline_data.all():
            itemline_invoice.itemline.stocked_item.available -= itemline_invoice.itemline.quantity
            itemline_invoice.itemline.stocked_item.save()

    def increment_stock(self):
        for itemline_invoice in self.order.itemline_data.all():
            itemline_invoice.itemline.stocked_item.available += itemline_invoice.itemline.quantity
            itemline_invoice.itemline.stocked_item.save()

    def cancel_order(self, canceled_by, reason):
        if self.canceled and self.canceled_date:
            return False
        self.canceled = True
        self.canceled_date = timezone.now()
        self.canceled_by = canceled_by
        self.cancel_reason = reason
        self.increment_stock()
        self.save()
        return True

    def _change_status(self):
        if self.status == self._old_status:
            return
        if self.status > self._old_status:
            self.date_modified = timezone.now()
            self._old_status = self.status
        elif self.status < self._old_status:
            self.status = self._old_status

    def get_due_date(self):
        # if self.date_confirmed:
        #     return self.date_confirmed + \
        #            datetime.timedelta(hours=float(self.order.get_shipping_cost()['delivery_time']))
        return self.date_confirmed

    def __unicode__(self):
        return self.tracking_number

    # def send_invoice_email(self):
    #     if self.get_status_display().lower() == "pending":
    #         send_invoice_mail(to=[self.order.associated_store.email,
    #                               self.buyer.email,
    #                               settings.CONNECT_EMAIL],
    #                           invoice=self.order)

    # def create_cron_job_delivery_email(self):
    #     # schedule job
    #     task, time = get_delivery_cron_command(self)
    #     os.system("echo %s | at %s" % (task, time))
    #
    # def send_order_confirm_email(self):
    #     if self.get_status_display().lower() == "confirmed" and self._old_status == 0:
    #         self.date_confirmed = timezone.now()
    #         send_order_confirm_mail(to=[self.order.associated_store.email,
    #                                     self.buyer.email],
    #                                 invoice=self.order)
    #         self.delivery_date = self.get_due_date()
    #
    #         self.create_cron_job_delivery_email()
    #
    # def send_order_enroute_email(self):
    #     # send mail with tracking number
    #     pass
    #
    # def send_delivery_email(self):
    #     send_order_due_delivery_mail(to=[self.buyer.email],
    #                                  invoice=self.order)

    def save(self, *args, **kwargs):
        if not self.id:
            self.status = getattr(self, 'status') or 0
            self._old_status = getattr(self, '_old_status') or 0
            self.date_modified = timezone.now()
            self.reduce_stock()
            # send mail
            # self.send_invoice_email()
        else:
            # self.send_order_confirm_email()
            self._change_status()
            # if 'rating' in kwargs.keys():
            #     self.update_ratings(**kwargs.pop('rating'))

        return super(TrackingDetails, self).save(*args, **kwargs)

    objects = TrackingDetailsManager()

    class Meta:
        ordering = ('order_placed', )


class OutletOrderDetails(CustomModel):
    """
    order detail will simply collect an entire, multiple tracking details from a particular user
    """
    order_number = models.CharField(max_length=15, null=False, unique=True)
    trackers = models.ManyToManyField(TrackingDetails)

    @property
    def buyer(self):
        # take first tracker and return its user.
        try:
            return self.trackers.all()[0].buyer
        except IndexError:
            return None

    def get_buyer(self):
        # take first tracker and return its user.
        try:
            return self.trackers.all()[0].buyer
        except IndexError:
            return None

    def send_mail(self):
        pass
        # todo sending to both the client and store

    def __str__(self):
        # except AttributeError:
        return str(self.id)

    def save(self, *args, **kwargs):
        if not self.id:
            self.order_number = 'O' + get_random_secret_key(10)
        elif self.id and not self.buyer:
            raise AttributeError(_("Empty Cart or Null Buyer..."), code="invalid")
        return super(OutletOrderDetails, self).save(*args, **kwargs)


@receiver(post_save, sender=TrackingDetails)
def add_tracking_num(sender, instance, created=True, **kwargs):
    if isinstance(instance, TrackingDetails):
        if not instance.tracking_number:
            instance.tracking_number = 'T-' + str(instance.id)
            instance.save()

templates/orders/list_orders.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="box">
        <div class="box-info" style="position: relative; left: 0px; top: 0px;">
            <div class="box-body">
                <form action="" method="get" id="search-form">
                    <div class="form-group">
    {#                            remove this dont#}
                    </div>
                    <div>
                        <div class="form-group">
                            <div class="col-md-3 col-sm-3">
                                <label class="col-md-3 col-sm-3 control-label">Order: </label>
                                <div class="col-md-9 col-sm-9">
                                    <input class="form-control" id="id_order" name="order"/>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-3">
                                <label class="col-md-3 col-sm-3 control-label">Status: </label>
                                <div class="col-md-9 col-sm-9">
                                    <select class="form-control" id="id_status" name="status">
                                        <option value="" selected="selected">---------</option>
                                        {% for c in status_choices %}
                                            <option value={{ c.0 }}>{{ c.1 }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-3">
                            <label class="col-md-3 col-sm-3">Shipped to: </label>
                                <div class="col-md-9 col-sm-9">
                                    <input class="form-control" id="id_customer" name="customer"/>
                                </div>
                            </div>
                        <div class="col-md-3 col-sm-3">
                            <label class="col-md-3 col-sm-3">Order Placed Date: </label>
                                <div class="col-md-9 col-sm-9">
                                    <input class="form-control" id="id_order_placed" name="order_placed"/>
                                </div>
                            </div>
                        </div>
                        <input type="submit" class="btn btn-primary" id="search" value="Search"/>
                    </div>
                </form>
            </div>
        </div>
        <div class="box-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="width: 140px">Invoice#</th>
                        <th style="width: 25%">Customer Information</th>
                        <th>Order#</th>
                        <th>Order Amount</th>
                        <th style="width: 140px">Tracking#</th>
                        <th>Status</th>
                        <th>Order Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tracker in object_list %}
                    <tr>
                        <td>
                            {{ tracker.order.invoice_number }}
                        </td>
                        <td>
                            <div class="invoice-col">
                                <address>
                                    <strong>{{ tracker.shipped_to|title }}</strong><br>
{#                                    {% if tracker.shipped_to.type == 'apartment' %}#}
{#                                    ap#{{ tracker.shipped_to.apartment|title }}, ro#{{ tracker.shipped_to.room|title }}, bd#{{ tracker.shipped_to.building|title }} <br>#}
{#                                    {% elif tracker.shipped_to.type == 'villa' %}#}
{#                                    Building: {{ tracker.shipped_to.building|title }} <br>#}
{#                                    {% else %}#}
{#                                    Company: {{ tracker.shipped_to.company|title }} <br>#}
{#                                    {% endif %}#}
{#                                    {{ tracker.shipped_to.street|title }}, {{ tracker.shipped_to.area|title }} <br>#}
{#                                    {{ tracker.shipped_to.city|title }}, {{ tracker.shipped_to.country|title }} <br>#}
{#                                    Near {{ tracker.shipped_to.nearest_landmark|title }}<br>#}
{#                                    Phone: {{ tracker.shipped_to.mobile_number|title }}<br>#}
{#                                    Email: {{ tracker.shipped_to.alternative_email|title }}#}
                                    Customer
                                    Info
                                    here
                                </address>
                            </div>
                        </td>
                        <td>
                            {{ tracker.order.id }}
                        </td>
                        <td>
                            {{ tracker.order.grand_total }}
                        </td>
                        <td>
                            {{ tracker.tracking_number }}
                            {% if tracker.get_status_display != "Delivered" %}
                                <a class="btn-sm" href="#">
                                    <i class="fa fa-edit"></i> Edit
                                </a>
                            {% endif %}
                        </td>
                        </td>
                        <td>
                            <b>{{ tracker.get_status }}</b>
                        </td>
                        <td>
                            {{ tracker.order_placed }}<br>
                            <u><small>DUE:<strong>{{ tracker.delivery_date }}</strong></small></u>
                        </td>
                        <td>
                            <p>
                                <a href="{% url 'outlets:orders:invoice:detail' outlet_id=outlet_id pk=tracker.order.pk %}">
                                    View Order
                                </a>
                            </p>
                            <a href="{% url 'outlets:orders:invoice:pdf' outlet_id=outlet_id pk=tracker.order.pk %}">
                                <p>View PDF</p>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div><!-- /.box-body -->
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                {% if page_obj.has_previous %}
                    <a type="button" class="btn btn-success" href="{% url 'outlets:orders:list' outlet_id=outlet.id %}?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}">
                        <span><< Previous</span>
                    </a>
                {% else %}
                    <span class="btn btn-default">
                        <span><< Previous</span>
                    </span>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a class="btn btn-success" href="{% url 'outlets:orders:list' store_id=store.id %}?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">
                        <span>Next >></span>
                    </a>
                {% else %}
                    <span class="btn btn-default">
                        <span>Next >></span>
                    </span>
                {% endif %}
            </span>
        </div>
        {% endif %}
    </div>
{% endblock %}